Plot_ErrorBars<-function(x, y, x.err, y.err, xbar = F,                                                                                                                                                                 
                          ybar = F, cap.scaling = 50, xcolor = "black",                                                                                                                                                
                          ycolor = "black", lwidth = 1, ...){                                                                                                                                                          
       ycap.width <- (par("usr")[4] - par("usr")[3])/cap.scaling                                                                                                                                                       
       xcap.width <- (par("usr")[2] - par("usr")[1])/cap.scaling                                                                                                                                                       
       if(xbar == T){                                                                                                                                                                                                  
             for(i in 1:length(x.err)){                                                                                                                                                                                
                   segments(x0 = x[i] + x.err[i], y0 = y[i],                                                                                                                                                           
                            x1= x[i] - x.err[i],  y1 = y[i],                                                                                                                                                           
                            lwd = lwidth, col = xcolor)                                                                                                                                                                
                   segments(x0 = x[i] + x.err[i], y0 = y[i] + ycap.width,                                                                                                                                              
                            x1=x[i] + x.err[i],   y1 = y[i] - ycap.width,                                                                                                                                              
                            lwd = lwidth, col = xcolor)                                                                                                                                                                
                   segments(x0 = x[i] - x.err[i], y0 = y[i] + ycap.width,                                                                                                                                              
                            x1=x[i] - x.err[i],   y1 = y[i] - ycap.width,                                                                                                                                              
                            lwd = lwidth, col = xcolor)                                                                                                                                                                
                 }                                                                                                                                                                                                     
               }                                                                                                                                                                                                       
               if(ybar == T){                                                                                                                                                                                          
                     for(i in 1:length(y.err)){                                                                                                                                                                        
                           segments(x0 = x[i], y0 = y[i] + y.err[i],                                                                                                                                                   
                                    x1= x[i],  y1 = y[i] - y.err[i],                                                                                                                                                   
                                    lwd = lwidth, col = ycolor)                                                                                                                                                        
                           segments(x0 = x[i] + xcap.width, y0 = y[i] + y.err[i],                                                                                                                                      
                                    x1=x[i] - xcap.width,   y1 = y[i] + y.err[i],                                                                                                                                      
                                    lwd = lwidth, col = ycolor)                                                                                                                                                        
                           segments(x0 = x[i] + xcap.width, y0 = y[i] - y.err[i],                                                                                                                                      
                                    x1=x[i] - xcap.width,   y1 = y[i] - y.err[i],                                                                                                                                      
                                    lwd = lwidth, col = ycolor)                                                                                                                                                        
                         }                                                                                                                                                                                             
                       }                                                                                                                                                                                               
                     }                                                                                                                                                                                                 
y_axis_sd <- c()                                                                                                                                                                                                       
y_axis_mean <- c()                                                                                                                                                                                                     
qt1 <- read.table("manipulated16.bed", header = T, sep = "\t")                                                                                                                                                         
y_axis_sd <- c(y_axis_sd, sd(qt1[,2]))                                                                                                                                                                                 
y_axis_mean <- c(y_axis_mean, mean(qt1[,2]))                                                                                                                                                                           
qt2 <- read.table("manipulated11.bed", header = T, sep = "\t")                                                                                                                                                         
y_axis_sd <- c(y_axis_sd, sd(qt2[,2]))                                                                                                                                                                                 
y_axis_mean <- c(y_axis_mean, mean(qt2[,2]))                                                                                                                                                                           
qt3 <- read.table("manipulated12.bed", header = T, sep = "\t")                                                                                                                                                         
y_axis_sd <- c(y_axis_sd, sd(qt3[,2]))                                                                                                                                                                                 
y_axis_mean <- c(y_axis_mean, mean(qt3[,2]))                                                                                                                                                                           
qt4 <- read.table("manipulated13.bed", header = T, sep = "\t")                                                                                                                                                         
y_axis_sd <- c(y_axis_sd, sd(qt4[,2])) 
y_axis_mean <- c(y_axis_mean, mean(qt4[,2]))                                                                                                                                                                           
qt5 <- read.table("manipulated14.bed", header = T, sep = "\t")                                                                                                                                                         
y_axis_sd <- c(y_axis_sd, sd(qt5[,2]))                                                                                                                                                                                 
y_axis_mean <- c(y_axis_mean, mean(qt5[,2]))                                                                                                                                                                           
qt6 <- read.table("manipulated15.bed", header = T, sep = "\t")                                                                                                                                                         
y_axis_sd <- c(y_axis_sd, sd(qt6[,2]))                                                                                                                                                                                 
y_axis_mean <- c(y_axis_mean, mean(qt6[,2]))                                                                                                                                                                           
qt7 <- read.table("manipulated20.bed", header = T, sep = "\t")                                                                                                                                                         
y_axis_sd <- c(y_axis_sd, sd(qt7[,2]))                                                                                                                                                                                 
y_axis_mean <- c(y_axis_mean, mean(qt7[,2]))                                                                                                                                                                           
qt8 <- read.table("manipulated17.bed", header = T, sep = "\t")                                                                                                                                                         
y_axis_sd <- c(y_axis_sd, sd(qt8[,2]))                                                                                                                                                                                 
y_axis_mean <- c(y_axis_mean, mean(qt8[,2]))                                                                                                                                                                           
qt9 <- read.table("manipulated19.bed", header = T, sep = "\t")                                                                                                                                                         
y_axis_sd <- c(y_axis_sd, sd(qt9[,2]))                                                                                                                                                                                 
y_axis_mean <- c(y_axis_mean, mean(qt9[,2]))                                                                                                                                                                           
qt10 <- read.table("manipulated18.bed", header = T, sep = "\t")                                                                                                                                                        
y_axis_sd <- c(y_axis_sd, sd(qt10[,2]))                                                                                                                                                                                
y_axis_mean <- c(y_axis_mean, mean(qt10[,2]))                                                                                                                                                                          
C_alpha <- c(0,1,2,3,4,5,8,10,15,20)                                                                                                                                                                                   
pdf("error_bar_plot.pdf")                                                                                                                                                                                              
plot(C_alpha, y_axis_mean, pch = 20,ylim = c(0, 1))                                                                                                                                                                    
data <- data.frame("0" = qt1[,2],                                                                                                                                                                                      
"1" = qt2[,2],                                                                                                                                                                                                         
"2" = qt3[,2],                                                                                                                                                                                                         
"3" = qt4[,2],                                                                                                                                                                                                         
"4" = qt5[,2],                                                                                                                                                                                                         
"5" = qt6[,2],                                                                                                                                                                                                         
"8" = qt7[,2],                                                                                                                                                                                                         
"10" = qt8[,2],                                                                                                                                                                                                        
"15" = qt9[,2],                                                                                                                                                                                                        
"20" = qt10[,2])                                                                                                                                                                                                       
Plot_ErrorBars(C_alpha, y_axis_mean, y.err = y_axis_sd, ybar = T )                                                                                                                                                     
pdf("error_bar_plot2.pdf")                                                                                                                                                                                             
boxplot(data, xlab = "C_alpha", ylab = "correlation coefficient", boxwex = 0.7, pch = 20)
